### ISSUE TITLE
Should the presence sensor return a bool, rather than a string?

### ISSUE THREAD

**Issue by LukeMondy** [sensy-one/S1#9]
For example: https://github.com/sensy-one/S1/blob/a99dde5d28d6909c14c958a0c55f040e3bcab597/assets/source/v1.0.4.yaml#L714

I'm unable to add the "any presence" sensor to my group of other presence sensors, and I think it's because they are binary sensors, while the S1 is a string. 

Can this be switched to a bool for occupancy, as per in here: https://www.home-assistant.io/integrations/binary_sensor/

Thanks!

**Comment by LukeMondy** [comment]
My other presence sensors are returning bools, it looks like: https://github.com/athom-tech/esp32-configs/blob/8b9b20eab4813cb904513b2c9af2306f3423d0a5/athom-presence-sensor-v3.yaml#L182

**Comment by LukeMondy** [comment]
For anyone else interested

I tried using the YAML in here: https://github.com/sensy-one/S1/blob/main/assets/source/v1.0.4.yaml, but ESPHome says that 'custom components' are no longer supported, so I was unable to build my own image.

In an attempt to fix this, I found that ESPHome has a component for the LD2450 sensor already: https://esphome.io/components/sensor/ld2450.html

I essentially copied their example, but will reproduce below just-in-case, and it works great. The issues seem to be:
- it doesn't support zone exceptions,
- the plotly visualisation doesn't work - see below for my YAML,
- unclear if it's as fast/responsive

However, it also does solve my original issue, which was around the presence sensor not returning a bool.

I put this YAML into ESPHome builder, build it, downloaded the firmware to my pc, and then uploaded it to the device as an OTA update.

```yaml
esphome:
  name: sensy-one-usb
  friendly_name: Sensy One USB
  name_add_mac_suffix: False
  project: 
    name: Sensy-One.S1 mmWave Sensor
    version: v1.0.4

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: 2.0.9

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "I am Sensy!"
    ap_timeout: 1min

captive_portal: 

api:
  encryption:
    key: "xxxxxxxxxx"

logger:
  level: DEBUG
  logs:
    default: ERROR
    sensor: ERROR
    text_sensor: ERROR
    template: ERROR
    uart: ERROR
    wifi: ERROR
    mdns: ERROR
    esphome.core: ERROR
    esp32_ble: ERROR
    esp32_ble_server: ERROR
    esp32_improv: ERROR
    captive_portal: ERROR
    web_server: ERROR
    api: ERROR
    ota: ERROR
    number: ERROR
    ld2450: DEBUG

web_server:
  port: 80
  log: false

ota:
  platform: esphome
  password: "xxxxxxx"

uart:
  id: uart_ld2450
  tx_pin: GPIO15  #RX-LD2450
  rx_pin: GPIO14  #TX-LD2450
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450
  throttle: 1000ms

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"
    zone_1:
      x1:
        name: Zone-1 X1
      y1:
        name: Zone-1 Y1
      x2:
        name: Zone-1 X2
      y2:
        name: Zone-1 Y2
    zone_2:
      x1:
        name: Zone-2 X1
      y1:
        name: Zone-2 Y1
      x2:
        name: Zone-2 X2
      y2:
        name: Zone-2 Y2
    zone_3:
      x1:
        name: Zone-3 X1
      y1:
        name: Zone-3 Y1
      x2:
        name: Zone-3 X2
      y2:
        name: Zone-3 Y2

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "Bluetooth"
    multi_target:
      name: Multi Target Tracking"

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "Baud rate"
    zone_type:
      name: "Zone Type"

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "LD2450 Factory Reset"
      entity_category: "config"
    restart:
      name: "LD2450 Restart"
      entity_category: "config"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450 Firmware"
    mac_address:
      name: "LD2450 BT MAC"
    target_1:
      direction:
        name: "Target-1 Direction"
    target_2:
      direction:
        name: "Target-2 Direction"
    target_3:
      direction:
        name: "Target-3 Direction"

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
  - platform: ld2450
    ld2450_id: ld2450_radar
    still_target_count:
      name: Still Target Count
  - platform: ld2450
    ld2450_id: ld2450_radar
    moving_target_count:
      name: Moving Target Count
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_1:
      x:
        name: Target-1 X
      y:
        name: Target-1 Y
      speed:
        name: Target-1 Speed
      angle:
        name: Target-1 Angle
      distance:
        name: Target-1 Distance
      resolution:
        name: Target-1 Resolution
    target_2:
      x:
        name: Target-2 X
      y:
        name: Target-2 Y
      speed:
        name: Target-2 Speed
      angle:
        name: Target-2 Angle
      distance:
        name: Target-2 Distance
      resolution:
        name: Target-2 Resolution
    target_3:
      x:
        name: Target-3 X
      y:
        name: Target-3 Y
      speed:
        name: Target-3 Speed
      angle:
        name: Target-3 Angle
      distance:
        name: Target-3 Distance
      resolution:
        name: Target-3 Resolution
    zone_1:
      target_count:
        name: Zone-1 All Target Count
      still_target_count:
        name: Zone-1 Still Target Count
      moving_target_count:
        name: Zone-1 Moving Target Count
    zone_2:
      target_count:
        name: Zone-2 All Target Count
      still_target_count:
        name: Zone-2 Still Target Count
      moving_target_count:
        name: Zone-2 Moving Target Count
    zone_3:
      target_count:
        name: Zone-3 All Target Count
      still_target_count:
        name: Zone-3 Still Target Count
      moving_target_count:
        name: Zone-3 Moving Target Count

```

Plotly:
```yaml
type: custom:plotly-graph
title: null
refresh_interval: 0.025
layout:
  height: 300
  margin:
    l: 50
    r: 35
    t: 15
    b: 67.5
  showlegend: false
  hovermode: false
  xaxis:
    dtick: 100
    type: number
    fixedrange: true
    showgrid: true
    showticklabels: true
    zeroline: false
    showline: false
    tickangle: -90
    tickfont:
      size: 14
    tickpadding: 10
    range:
      - -605
      - 605
  yaxis:
    dtick: 100
    type: number
    fixedrange: true
    showgrid: true
    showticklabels: true
    zeroline: true
    showline: false
    tickfont:
      size: 14
    tickpadding: 10
    range:
      - 605
      - 0
entities:
  - entity: ""
    name: Coverage
    type: scatter
    mode: lines
    showlegend: false
    line:
      shape: linear
      smoothing: 1
      width: 2
      color: grey
      dash: dot
    x: |
      $ex (function(){
        let pts = [], sx = 600 * Math.sin(60 * Math.PI/180);
        for (let t = 0; t <= 1; t += 0.1) pts.push(sx * t);
        for (let a = 60; a >= -60; a -= 2) pts.push(600 * Math.sin(a * Math.PI/180));
        let ex = 600 * Math.sin(-60 * Math.PI/180);
        for (let t = 1; t >= 0; t -= 0.1) pts.push(ex * t);
        return pts;
      })()
    "y": |
      $ex (function(){
        let pts = [], sy = 600 * Math.cos(60 * Math.PI/180);
        for (let t = 0; t <= 1; t += 0.1) pts.push(sy * t);
        for (let a = 60; a >= -60; a -= 2) pts.push(600 * Math.cos(a * Math.PI/180));
        let ey = 600 * Math.cos(-60 * Math.PI/180);
        for (let t = 1; t >= 0; t -= 0.1) pts.push(ey * t);
        return pts;
      })()
  - entity: ""
    name: Zone 1 Box
    type: scatter
    mode: lines
    showlegend: false
    line:
      color: rgb(100,100,100)
      width: 2
    x: |
      $ex [
        hass.states["number.sensy_one_usb_zone_1_x1"].state,
        hass.states["number.sensy_one_usb_zone_1_x2"].state,
        hass.states["number.sensy_one_usb_zone_1_x2"].state,
        hass.states["number.sensy_one_usb_zone_1_x1"].state,
        hass.states["number.sensy_one_usb_zone_1_x1"].state
      ]
    "y": |
      $ex [
        hass.states["number.sensy_one_usb_zone_1_y1"].state,
        hass.states["number.sensy_one_usb_zone_1_y1"].state,
        hass.states["number.sensy_one_usb_zone_1_y2"].state,
        hass.states["number.sensy_one_usb_zone_1_y2"].state,
        hass.states["number.sensy_one_usb_zone_1_y1"].state
      ]
  - entity: ""
    name: Zone 2 Box
    type: scatter
    mode: lines
    showlegend: false
    line:
      color: rgb(100,100,100)
      width: 2
    x: |
      $ex [
        hass.states["number.sensy_one_usb_zone_2_x1"].state,
        hass.states["number.sensy_one_usb_zone_2_x2"].state,
        hass.states["number.sensy_one_usb_zone_2_x2"].state,
        hass.states["number.sensy_one_usb_zone_2_x1"].state,
        hass.states["number.sensy_one_usb_zone_2_x1"].state
      ]
    "y": |
      $ex [
        hass.states["number.sensy_one_usb_zone_2_y1"].state,
        hass.states["number.sensy_one_usb_zone_2_y1"].state,
        hass.states["number.sensy_one_usb_zone_2_y2"].state,
        hass.states["number.sensy_one_usb_zone_2_y2"].state,
        hass.states["number.sensy_one_usb_zone_2_y1"].state
      ]
  - entity: ""
    name: Zone 3 Box
    type: scatter
    mode: lines
    showlegend: false
    line:
      color: rgb(100,100,100)
      width: 2
    x: |
      $ex [
        hass.states["number.sensy_one_usb_zone_3_x1"].state,
        hass.states["number.sensy_one_usb_zone_3_x2"].state,
        hass.states["number.sensy_one_usb_zone_3_x2"].state,
        hass.states["number.sensy_one_usb_zone_3_x1"].state,
        hass.states["number.sensy_one_usb_zone_3_x1"].state
      ]
    "y": |
      $ex [
        hass.states["number.sensy_one_usb_zone_3_y1"].state,
        hass.states["number.sensy_one_usb_zone_3_y1"].state,
        hass.states["number.sensy_one_usb_zone_3_y2"].state,
        hass.states["number.sensy_one_usb_zone_3_y2"].state,
        hass.states["number.sensy_one_usb_zone_3_y1"].state
      ]
  - entity: ""
    name: Zone 1 Label
    type: scatter
    mode: text
    showlegend: false
    text: |
      $ex (
        (parseFloat(hass.states["number.sensy_one_usb_zone_1_x1"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_1_x2"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_1_y1"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_1_y2"].state) === 0)
        ? ""
        : "Z1"
      )
    textfont:
      size: 12
      color: rgb(100,100,100)
    textposition: middle center
    x:
      - |-
        $ex (
          (parseFloat(hass.states["number.sensy_one_usb_zone_1_x1"].state) === 0 &&
           parseFloat(hass.states["number.sensy_one_usb_zone_1_x2"].state) === 0)
          ? null
          : ((parseFloat(hass.states["number.sensy_one_usb_zone_1_x1"].state) +
              parseFloat(hass.states["number.sensy_one_usb_zone_1_x2"].state)) / 2)
        )
    "y":
      - |-
        $ex (
          (parseFloat(hass.states["number.sensy_one_usb_zone_1_y1"].state) === 0 &&
           parseFloat(hass.states["number.sensy_one_usb_zone_1_y2"].state) === 0)
          ? null
          : ((parseFloat(hass.states["number.sensy_one_usb_zone_1_y1"].state) +
              parseFloat(hass.states["number.sensy_one_usb_zone_1_y2"].state)) / 2)
        )
  - entity: ""
    name: Zone 2 Label
    type: scatter
    mode: text
    showlegend: false
    text: |
      $ex (
        (parseFloat(hass.states["number.sensy_one_usb_zone_2_x1"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_2_x2"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_2_y1"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_2_y2"].state) === 0)
        ? ""
        : "Z2"
      )
    textfont:
      size: 12
      color: rgb(100,100,100)
    textposition: middle center
    x:
      - |-
        $ex (
          (parseFloat(hass.states["number.sensy_one_usb_zone_2_x1"].state) === 0 &&
           parseFloat(hass.states["number.sensy_one_usb_zone_2_x2"].state) === 0)
          ? null
          : ((parseFloat(hass.states["number.sensy_one_usb_zone_2_x1"].state) +
              parseFloat(hass.states["number.sensy_one_usb_zone_2_x2"].state)) / 2)
        )
    "y":
      - |-
        $ex (
          (parseFloat(hass.states["number.sensy_one_usb_zone_2_y1"].state) === 0 &&
           parseFloat(hass.states["number.sensy_one_usb_zone_2_y2"].state) === 0)
          ? null
          : ((parseFloat(hass.states["number.sensy_one_usb_zone_2_y1"].state) +
              parseFloat(hass.states["number.sensy_one_usb_zone_2_y2"].state)) / 2)
        )
  - entity: ""
    name: Zone 3 Label
    type: scatter
    mode: text
    showlegend: false
    text: |
      $ex (
        (parseFloat(hass.states["number.sensy_one_usb_zone_3_x1"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_3_x2"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_3_y1"].state) === 0 &&
         parseFloat(hass.states["number.sensy_one_usb_zone_3_y2"].state) === 0)
        ? ""
        : "Z3"
      )
    textfont:
      size: 12
      color: rgb(100,100,100)
    textposition: middle center
    x:
      - |-
        $ex (
          (parseFloat(hass.states["number.sensy_one_usb_zone_3_x1"].state) === 0 &&
           parseFloat(hass.states["number.sensy_one_usb_zone_3_x2"].state) === 0)
          ? null
          : ((parseFloat(hass.states["number.sensy_one_usb_zone_3_x1"].state) +
              parseFloat(hass.states["number.sensy_one_usb_zone_3_x2"].state)) / 2)
        )
    "y":
      - |-
        $ex (
          (parseFloat(hass.states["number.sensy_one_usb_zone_3_y1"].state) === 0 &&
           parseFloat(hass.states["number.sensy_one_usb_zone_3_y2"].state) === 0)
          ? null
          : ((parseFloat(hass.states["number.sensy_one_usb_zone_3_y1"].state) +
              parseFloat(hass.states["number.sensy_one_usb_zone_3_y2"].state)) / 2)
        )
  - entity: ""
    name: Target 1 Tail
    type: scatter
    mode: lines+markers
    showlegend: false
    line:
      shape: linear
      smoothing: 1
      width: 4
      color: rgba(78,53,206,1)
    marker:
      size: 6
      color: rgba(78,53,206,1)
    x: |
      $ex (function(){
        let x = parseFloat(hass.states["sensor.sensy_one_usb_target_1_x"].state);
        if(x === 0){
          window.target1TailX = [];
          return window.target1TailX;
        }
        window.target1TailX = window.target1TailX || [];
        window.target1TailX.push(x);
        if(window.target1TailX.length > 50){ window.target1TailX.shift(); }
        function smooth(arr, windowSize) {
          let result = [];
          for (let i = 0; i < arr.length; i++){
            let start = Math.max(0, i - Math.floor(windowSize/2));
            let end = Math.min(arr.length, i + Math.ceil(windowSize/2));
            let sum = 0;
            for(let j = start; j < end; j++){
              sum += arr[j];
            }
            result.push(sum/(end - start));
          }
          return result;
        }
        return smooth(window.target1TailX, 5);
      })()
    "y": |
      $ex (function(){
        let y = parseFloat(hass.states["sensor.sensy_one_usb_target_1_y"].state);
        if(y === 0){
          window.target1TailY = [];
          return window.target1TailY;
        }
        window.target1TailY = window.target1TailY || [];
        window.target1TailY.push(y);
        if(window.target1TailY.length > 50){ window.target1TailY.shift(); }
        function smooth(arr, windowSize) {
          let result = [];
          for (let i = 0; i < arr.length; i++){
            let start = Math.max(0, i - Math.floor(windowSize/2));
            let end = Math.min(arr.length, i + Math.ceil(windowSize/2));
            let sum = 0;
            for(let j = start; j < end; j++){
              sum += arr[j];
            }
            result.push(sum/(end - start));
          }
          return result;
        }
        return smooth(window.target1TailY, 5);
      })()
  - entity: ""
    name: Target 2 Tail
    type: scatter
    mode: lines+markers
    showlegend: false
    line:
      shape: linear
      smoothing: 1
      width: 4
      color: rgba(78,53,206,1)
    marker:
      size: 6
      color: rgba(78,53,206,1)
    x: |
      $ex (function(){
        let x = parseFloat(hass.states["sensor.sensy_one_usb_target_2_x"].state);
        if(x === 0){
          window.target2TailX = [];
          return window.target2TailX;
        }
        window.target2TailX = window.target2TailX || [];
        window.target2TailX.push(x);
        if(window.target2TailX.length > 50){ window.target2TailX.shift(); }
        function smooth(arr, windowSize) {
          let result = [];
          for (let i = 0; i < arr.length; i++){
            let start = Math.max(0, i - Math.floor(windowSize/2));
            let end = Math.min(arr.length, i + Math.ceil(windowSize/2));
            let sum = 0;
            for(let j = start; j < end; j++){
              sum += arr[j];
            }
            result.push(sum/(end - start));
          }
          return result;
        }
        return smooth(window.target2TailX, 5);
      })()
    "y": |
      $ex (function(){
        let y = parseFloat(hass.states["sensor.sensy_one_usb_target_2_y"].state);
        if(y === 0){
          window.target2TailY = [];
          return window.target2TailY;
        }
        window.target2TailY = window.target2TailY || [];
        window.target2TailY.push(y);
        if(window.target2TailY.length > 50){ window.target2TailY.shift(); }
        function smooth(arr, windowSize) {
          let result = [];
          for (let i = 0; i < arr.length; i++){
            let start = Math.max(0, i - Math.floor(windowSize/2));
            let end = Math.min(arr.length, i + Math.ceil(windowSize/2));
            let sum = 0;
            for(let j = start; j < end; j++){
              sum += arr[j];
            }
            result.push(sum/(end - start));
          }
          return result;
        }
        return smooth(window.target2TailY, 5);
      })()
  - entity: ""
    name: Target 3 Tail
    type: scatter
    mode: lines+markers
    showlegend: false
    line:
      shape: linear
      smoothing: 1
      width: 4
      color: rgba(78,53,206,1)
    marker:
      size: 6
      color: rgba(78,53,206,1)
    x: |
      $ex (function(){
        let x = parseFloat(hass.states["sensor.sensy_one_usb_target_3_x"].state);
        if(x === 0){
          window.target3TailX = [];
          return window.target3TailX;
        }
        window.target3TailX = window.target3TailX || [];
        window.target3TailX.push(x);
        if(window.target3TailX.length > 50){ window.target3TailX.shift(); }
        function smooth(arr, windowSize) {
          let result = [];
          for (let i = 0; i < arr.length; i++){
            let start = Math.max(0, i - Math.floor(windowSize/2));
            let end = Math.min(arr.length, i + Math.ceil(windowSize/2));
            let sum = 0;
            for(let j = start; j < end; j++){
              sum += arr[j];
            }
            result.push(sum/(end - start));
          }
          return result;
        }
        return smooth(window.target3TailX, 5);
      })()
    "y": |
      $ex (function(){
        let y = parseFloat(hass.states["sensor.sensy_one_usb_target_3_y"].state);
        if(y === 0){
          window.target3TailY = [];
          return window.target3TailY;
        }
        window.target3TailY = window.target3TailY || [];
        window.target3TailY.push(y);
        if(window.target3TailY.length > 50){ window.target3TailY.shift(); }
        function smooth(arr, windowSize) {
          let result = [];
          for (let i = 0; i < arr.length; i++){
            let start = Math.max(0, i - Math.floor(windowSize/2));
            let end = Math.min(arr.length, i + Math.ceil(windowSize/2));
            let sum = 0;
            for(let j = start; j < end; j++){
              sum += arr[j];
            }
            result.push(sum/(end - start));
          }
          return result;
        }
        return smooth(window.target3TailY, 5);
      })()
  - entity: ""
    name: Target 1
    type: scatter
    mode: markers+text
    marker:
      size: 12
      color: "#FFFFFF"
      symbol: circle
    text: >
      $ex ("T1 (" + hass.states["sensor.sensy_one_usb_target_1_speed"].state + "
      cm/s)")
    textfont:
      color: "#FFFFFF"
    textposition: top center
    x:
      - |-
        $ex (
          parseFloat(hass.states["sensor.sensy_one_usb_target_1_x"].state) === 0 &&
          parseFloat(hass.states["sensor.sensy_one_usb_target_1_y"].state) === 0
          ? null
          : parseFloat(hass.states["sensor.sensy_one_usb_target_1_x"].state)
        )
    "y":
      - |-
        $ex (
          parseFloat(hass.states["sensor.sensy_one_usb_target_1_x"].state) === 0 &&
          parseFloat(hass.states["sensor.sensy_one_usb_target_1_y"].state) === 0
          ? null
          : parseFloat(hass.states["sensor.sensy_one_usb_target_1_y"].state)
        )
  - entity: ""
    name: Target 2
    type: scatter
    mode: markers+text
    marker:
      size: 12
      color: "#FFFFFF"
      symbol: circle
    text: >
      $ex ("T2 (" + hass.states["sensor.sensy_one_usb_target_2_speed"].state + "
      cm/s)")
    textfont:
      color: "#FFFFFF"
    textposition: top center
    x:
      - |-
        $ex (
          parseFloat(hass.states["sensor.sensy_one_usb_target_2_x"].state) === 0 &&
          parseFloat(hass.states["sensor.sensy_one_usb_target_2_y"].state) === 0
          ? null
          : parseFloat(hass.states["sensor.sensy_one_usb_target_2_x"].state)
        )
    "y":
      - |-
        $ex (
          parseFloat(hass.states["sensor.sensy_one_usb_target_2_x"].state) === 0 &&
          parseFloat(hass.states["sensor.sensy_one_usb_target_2_y"].state) === 0
          ? null
          : parseFloat(hass.states["sensor.sensy_one_usb_target_2_y"].state)
        )
  - entity: ""
    name: Target 3
    type: scatter
    mode: markers+text
    marker:
      size: 12
      color: "#FFFFFF"
      symbol: circle
    text: >
      $ex ("T3 (" + hass.states["sensor.sensy_one_usb_target_3_speed"].state + "
      cm/s)")
    textfont:
      color: "#FFFFFF"
    textposition: top center
    x:
      - |-
        $ex (
          parseFloat(hass.states["sensor.sensy_one_usb_target_3_x"].state) === 0 &&
          parseFloat(hass.states["sensor.sensy_one_usb_target_3_y"].state) === 0
          ? null
          : parseFloat(hass.states["sensor.sensy_one_usb_target_3_x"].state)
        )
    "y":
      - |-
        $ex (
          parseFloat(hass.states["sensor.sensy_one_usb_target_3_x"].state) === 0 &&
          parseFloat(hass.states["sensor.sensy_one_usb_target_3_y"].state) === 0
          ? null
          : parseFloat(hass.states["sensor.sensy_one_usb_target_3_y"].state)
        )

```
